/* Modelagem fisica*/ 

CREATE DATABASE PROJETO; 
/*Conectar ao banco*/ 
USE PROJETO;
/*Criar a tabela de clientes*/ 
CREATE TABLE CLIENTE(
    NOME VARCHAR(30), 
    SEXO CHAR(1), 
    EMAIL VARCHAR(30), 
    NIF INT(11),
    TELEFONE VARCHAR(30),
    MORADA VARCHAR(100)
); 

/* Ver as tabelas do banco de dados*/ 
SHOW TABLES;
/*Descriçao da tabela*/ 
DESC CLIENTE; 

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',1245678912,
'936127474','FAFE');

/*projeçao -> Select */ 

SELECT NOW(); 
SELECT 'JOAO'; 

SELECT NOW() as Agora, 'Joao' as PROF; /*dar nome ás variaveis*/

/* mostra as colunas */ 
SELECT NOME, SEXO, EMAIL FROM CLIENTE; 
SELECT NOME as Cliente, SEXO, EMAIL FROM CLIENTE; 
SELECT * FROM CLIENTE; /*SELECIONA TUDO DA TABELA, USAR SO NA UNIVERSIDADE*/ 

/*Select com filtro*/ 
SELECT NOME, SEXO, EMAIL FROM CLIENTE
WHERE SEXO = 'M'; /*Filtrado por sexo*/

/*Usando o like*/ 
SELECT NOME, SEXO, MORADA FROM CLIENTE
WHERE MORADA LIKE '%FAFE'; /*FAFE ESTA CONTIDA NA MORADA -> QUALQUER COISA FAFE */ 

SELECT NOME, SEXO, MORADA FROM CLIENTE
WHERE MORADA LIKE 'FAFE%'; /*FAFE ESTA CONTIDA NA MORADA ->FAFE QUALQUER COISA  */ 


